Moves to GitHub actions build (#188) (#183) (#187)
* Travis is still cutoff despite over a week of email.
 * We have to switch to GitHub actions to avoid paralyzing the project

As a part of this, the build is refactored to use common scripts,
documented in build-bin/README.md

diff --git a/build-bin/maven/maven_opts b/build-bin/maven/maven_opts
--- a/build-bin/maven/maven_opts
+++ b/build-bin/maven/maven_opts
@@ -13,8 +13,29 @@
 # the License.
 #
 
-# ENTRYPOINT script that runs the dependencies job on-demand, processing today's spans unless CLI
-# args override it (Ex. 2020-10-31)
-set -eu
+# This script checks each variable value, so it isn't important to fail on unbound (set -u)
+set -e
 
-exec java ${JAVA_OPTS} -Djava.io.tmpdir=/tmp -cp classes zipkin2.dependencies.ZipkinDependenciesJob $@
+maven_project_basedir=${MAVEN_PROJECT_BASEDIR:-.}
+pom="${maven_project_basedir}/pom.xml"
+
+# fail if there's no pom
+test -f "${pom}"
+
+arch=$(uname -m)
+case ${arch} in
+  arm64* )
+    arch=arm64
+    ;;
+  aarch64* )
+    arch=arm64
+    ;;
+esac
+
+maven_opts=""
+if [ ${arch} = "arm64" ] && [ -f /etc/alpine-release ]; then
+  # Defensively avoid arm64+alpine problems with posix_spawn
+  maven_opts="-Djdk.lang.Process.launchMechanism=vfork"
+fi
+
+echo ${maven_opts}
